#ifndef SOUND_CHANNEL_H
#define SOUND_CHANNEL_H

enum class GUN_SOUND_CHANNEL
{
    GUN_SHOOT_1,
    GUN_SHOOT_2,
    GUN_SHOOT_3,
    GUN_SHOOT_4,

    GUN_PULL_OUT_AND_RELOAD,

    NEXT,
    COUNT = NEXT
};

enum class BOSS_SOUND_CHANNEL
{
    WING_FLAP_1 = (int)GUN_SOUND_CHANNEL::NEXT,
    WING_FLAP_2,
    WING_FLAP_3,

    SYRINGE_1,
    SYRINGE_2,

    NEXT,
    COUNT = NEXT - (int)GUN_SOUND_CHANNEL::NEXT
};

enum class MAINBIRD_SOUND_CHANNEL
{
    JUMP = (int)BOSS_SOUND_CHANNEL::NEXT,
    COLLISION,
    FAST_HEART,

    NEXT,
    COUNT = NEXT - (int)BOSS_SOUND_CHANNEL::NEXT
};

enum class ITEM_SOUND_CHANNEL
{
    ITEM_PICKUP = (int)MAINBIRD_SOUND_CHANNEL::NEXT,

    NEXT,
    COUNT = NEXT - (int)MAINBIRD_SOUND_CHANNEL::NEXT
};

enum class SOUND_CHANNEL_COUNT
{
    GAME = (int)GUN_SOUND_CHANNEL::COUNT + (int)BOSS_SOUND_CHANNEL::COUNT
          +(int)MAINBIRD_SOUND_CHANNEL::COUNT + (int)ITEM_SOUND_CHANNEL::COUNT
};

#endif